on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu18.04
        install: |
          set -e
          apt-get update
          apt-get install --no-install-recommends -y python3
          python3 -m ensurepip
          pip3 install --upgrade pip setuptools pytest
        run: pwd && python3 -c "import os; print(os.uname())"