on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu18.04
        install: |
          set -e
          apt-get update
          apt-get install -y python3-pip
        run: python3 -c "import os; print(os.uname())"