on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu18.04
        install: |
          set -e
          apt-get update
          apt-get install --no-install-recommends -y ca-certificates curl make python3-distutils
          curl -O https://bootstrap.pypa.io/pip/3.6/get-pip.py
          python3 get-pip.py
        run: |
          python3 -m pip install eyes-images
          python3 -m applitools.eyes_universal --version